---
name: Image Digest
description: A Buildkite plugin to retrieve the digest of a specified image
author: https://github.com/equinixmetal-buildkite
requirements:
  - docker
configuration:
  properties:
    image:
      type: string
  required:
    - image