name: image-digest
description: A Buildkite plugin to retrieve the digest of a specified image
author: https://github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    image:
      type: string
  required:
    - image